### ISSUE TITLE
Link each programming language in the list to its own website.

### ISSUE THREAD

**Issue by BDadmehr0** [agnilondapakou/helloWorld#116]
For example: 
```
1. [Python](https://www.python.org/)
2. [C](https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html) 
3. [java](https://www.java.com/)
```
- Some programming languages don't have official websites, like the C language, etc. Therefore, you can use websites created by the communities of these languages.
- It is better to address this issue after finishing adding all the programming languages.

**Comment by harsha094** [comment]
Great task please assign it to me

**Comment by agnilondapakou** [comment]
Thanks to @BDadmehr0 for this good issue.
