### ISSUE TITLE
Add Haxe programming language in readme file.

### ISSUE THREAD

**Issue by agnilondapakou** [agnilondapakou/helloWorld#142]

**Comment by harsha094** [comment]
Assign it to me Sir

**Comment by apsharma07** [comment]
@harsha094 its Haxe programming language check it before adding in readme file. It's my mistake.

**Comment by agnilondapakou** [comment]
Ok.

Thanks for precision.

**Comment by harsha094** [comment]
@apsharma07 Thank you for the clarification
