### ISSUE TITLE
Add Common Lisp in available languages in readme file.

### ISSUE THREAD

**Issue by agnilondapakou** [agnilondapakou/helloWorld#156]

**Comment by abstractHunter** [comment]
Hello, is this task about moving the lisp helloworld program from main directory to source directory and add it to the readme ?
If so you can assign it to me, thanks.

**Comment by agnilondapakou** [comment]
No.

This task is about adding Common Lisp in avalable languages in readme file.

**Comment by parthivsaikia** [comment]
can you assign me this issue
