### ISSUE TITLE
Add Purescript in available languages in readme file.

### ISSUE THREAD

**Issue by agnilondapakou** [agnilondapakou/helloWorld#169]

**Comment by JP-sDEV** [comment]
Could I be assigned to this issue?

**Comment by amit712singhal** [comment]
Can you assign this to me? I would like to work on this issue.

**Comment by agnilondapakou** [comment]
Are you sure ?

**Comment by JP-sDEV** [comment]
Yes, here is the link: https://github.com/agnilondapakou/helloWorld/blob/main/source/basic/HelloWorld.purs

**Comment by JP-sDEV** [comment]
Oh it isn't, my apologies. Will update!

**Comment by agnilondapakou** [comment]
Good. I'm seeing that Purescript is not listed in readme file at available languages section.
