### ISSUE TITLE
Add Zig Language Support

### ISSUE THREAD

**Issue by BDadmehr0** [agnilondapakou/helloWorld#173]
I would like to propose adding support for the Zig programming language to our "Hello World" project.

**Comment by agnilondapakou** [comment]
Thank you for contribution.

Do you want to work on this task ?

**Comment by BDadmehr0** [comment]
> Thank you for contribution.
> 
> Do you want to work on this task ?

Yes

**Comment by agnilondapakou** [comment]
Good

**Comment by BDadmehr0** [comment]
I realized that this language was added before.
