### ISSUE TITLE
Improvement of the process

### ISSUE THREAD

**Issue by BDadmehr0** [agnilondapakou/helloWorld#176]
1. It is possible to link to your file paths in the repository within the list of programming languages in the README.md.
2. This [list](https://en.wikipedia.org/wiki/List_of_programming_languages) can help with adding new languages

**Comment by agnilondapakou** [comment]
Yeah, good idea @BDadmehr0.

Do you want to work on this issue ?

**Comment by BDadmehr0** [comment]
> Do you want to work on this issue ?

link to  file paths ?

**Comment by agnilondapakou** [comment]
Yes.

**Comment by BDadmehr0** [comment]
yes working on it

**Comment by agnilondapakou** [comment]
Good
