### ISSUE TITLE
Sort languages in Readme alphabetically

### ISSUE THREAD

**Issue by abstractHunter** [agnilondapakou/helloWorld#234]
Hello, i think it will be easier to find which languages are already added and which ones could be if the available languages are sorted alphabetically.
If this is ok and approved, you can assign this issue to me and add the hacktoberfest tag to it.

**Comment by agnilondapakou** [comment]
Good issue @abstractHunter .

Thanks for contribution.

Do you whant to work on it ?

**Comment by 0xParcival** [comment]
can you assign me?

**Comment by 0xParcival** [comment]
[#241](https://github.com/agnilondapakou/helloWorld/pull/241)

**Comment by abstractHunter** [comment]
Yeah of course.
