### ISSUE TITLE
Add entire HTML content

### ISSUE THREAD

**Issue by Docteur-Parfait** [agnilondapakou/helloWorld#29]
You have to add all HMTL content, not just the h1

**Comment by Just2sire** [comment]
Do you wanna say every tag in HTML !?😅

**Comment by Docteur-Parfait** [comment]
Yesss 😅

**Comment by agnilondapakou** [comment]
@Just2sire can you add the entier content to HTML file ?

**Comment by Just2sire** [comment]
I don't think so😅. Threre are too many things
