### ISSUE TITLE
Add "Hello world" in Clojure programming language.

### ISSUE THREAD

**Issue by agnilondapakou** [agnilondapakou/helloWorld#87]

**Comment by HamidRezaAshkiyan** [comment]
Can you assign this to me?

**Comment by Abhinav771** [comment]
Hi! @agnilondapakou, I can add "Hello" in  Clojure programming language. Can you please assign this to me.

**Comment by parthivsaikia** [comment]
Sir, this problem is still unsolved can you please assign the issue to me

**Comment by amit712singhal** [comment]
Can you assign this to me? I would like to work on this issue.
